image: node:20-alpine

variables:
  NODE_ENV: "test"

stages:
  - lint
  - test
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull-push

.node_setup: &node_setup
  before_script:
    - node --version
    - npm --version
    - npm ci --prefer-offline

lint:
  stage: lint
  <<: *node_setup
  script:
    - npm run lint
    - npx tsc --noEmit
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
    - if: '$CI_COMMIT_BRANCH =~ /^bonus\//'
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix\//'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:unit:
  stage: test
  <<: *node_setup
  variables:
    NODE_ENV: "test"
    JEST_JUNIT_OUTPUT_DIR: "reports/unit"
    JEST_JUNIT_OUTPUT_NAME: "junit.xml"
  script:
    - npx jest --testPathPattern="tests/unit" --forceExit --runInBand --coverage --coverageReporters=text --coverageReporters=cobertura
  coverage: '/Lines\s*:\s*(\d+(?:\.\d+)?%)/'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
    - if: '$CI_COMMIT_BRANCH =~ /^bonus\//'
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix\//'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    when: always
    reports:
      junit: reports/unit/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week

test:integration:
  stage: test
  <<: *node_setup
  services:
    - name: mongo:7.0
      alias: mongodb
  variables:
    NODE_ENV: "test"
    MONGO_URI: "mongodb://mongodb:27017/taskflow_ci"
    JWT_SECRET: "ci-test-secret-32-chars-long-abc"
    JWT_REFRESH_SECRET: "ci-refresh-secret-32-chars-long-abc"
    JWT_EXPIRES_IN: "15m"
    JWT_REFRESH_EXPIRES_IN: "7d"
    JEST_JUNIT_OUTPUT_DIR: "reports/integration"
    JEST_JUNIT_OUTPUT_NAME: "junit.xml"
  before_script:
    - node --version
    - npm --version
    - npm ci --prefer-offline
    - sleep 5
  script:
    - npx jest --testPathPattern="tests/integration" --forceExit --runInBand
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    when: always
    reports:
      junit: reports/integration/junit.xml
    expire_in: 1 week

build:
  stage: build
  <<: *node_setup
  script:
    - npm run build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
