import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { ITask } from '@/types/models.types';

export interface PdfReportOptions {
  title: string;
  tasks: ITask[];
  generatedBy?: string;
}

export async function generateTaskReportPdf(
  options: PdfReportOptions,
  res: Response,
): Promise<void> {
  const { title, tasks, generatedBy = 'TaskFlow API' } = options;

  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="task-report-${Date.now()}.pdf"`,
  );

  doc.pipe(res);


  doc
    .fontSize(24)
    .font('Helvetica-Bold')
    .text(title, { align: 'center' });

  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#555555')
    .text(`Generated by: ${generatedBy}  |  ${new Date().toLocaleDateString('en-GB')}`, {
      align: 'center',
    });

  doc.moveDown(1.5);
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .strokeColor('#cccccc')
    .stroke();
  doc.moveDown(1);


  const statusCounts = tasks.reduce<Record<string, number>>((acc, t) => {
    acc[t.status] = (acc[t.status] ?? 0) + 1;
    return acc;
  }, {});

  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#000000')
    .text('Summary', { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(10).font('Helvetica');
  doc.text(`Total tasks: ${tasks.length}`);
  for (const [status, count] of Object.entries(statusCounts)) {
    doc.text(`  • ${status}: ${count}`);
  }
  doc.moveDown(1);


  doc
    .fontSize(12)
    .font('Helvetica-Bold')
    .fillColor('#000000')
    .text('Tasks', { underline: true });
  doc.moveDown(0.5);

  if (tasks.length === 0) {
    doc.fontSize(10).font('Helvetica').text('No tasks found.');
  }

  tasks.forEach((task, index) => {
    if (doc.y > 700) {
      doc.addPage();
    }

    const statusColour =
      task.status === 'done'
        ? '#27ae60'
        : task.status === 'in-progress'
          ? '#2980b9'
          : task.status === 'review'
            ? '#e67e22'
            : '#7f8c8d';

    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#000000')
      .text(`${index + 1}. ${task.title}`, { continued: true })
      .font('Helvetica')
      .fillColor(statusColour)
      .text(`  [${task.status.toUpperCase()}]`);

    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#555555')
      .text(`Priority: ${task.priority}  |  Due: ${task.dueDate ? new Date(task.dueDate).toLocaleDateString('en-GB') : 'N/A'}`);

    if (task.description) {
      doc
        .fontSize(9)
        .fillColor('#333333')
        .text(task.description, { indent: 12 });
    }

    doc.moveDown(0.8);
  });

  doc.end();
}

export async function generateTaskReportCsv(tasks: ITask[]): Promise<string> {
  const header = 'id,title,status,priority,dueDate,createdAt\n';
  const rows = tasks
    .map((t) => {
      const due = t.dueDate ? new Date(t.dueDate).toISOString().split('T')[0] : '';
      const created = new Date(t.createdAt).toISOString().split('T')[0];
      const title = `"${String(t.title).replace(/"/g, '""')}"`;
      return `${String(t._id)},${title},${t.status},${t.priority},${due},${created}`;
    })
    .join('\n');
  return header + rows;
}
